---
name: 🚀 Feature request
description: Suggest an idea to make FreeSewing better
title: '[feature]: '
labels: [':gem: enhancement']
body:
  - type: markdown
    attributes:
      value: "You've got a great idea to make FreeSewing better? Tell us all about it :point_down:"
  - type: textarea
    id: desc
    attributes:
      label: 'What is it that you would like to see happen? 🤔'
      description: Please provide a clear and concise description of what you want to happen
      placeholder: |
        I would like to be able to export patterns as a Gitlab snippet, just like they can be exported as a Github gist
  - type: dropdown
    id: patron
    attributes:
      label: Are you a FreeSewing patron? 😃
      description: 'Patrons support us financially :pray: so they get priority'
      options:
        - 'Yes, I am a tier-2 patron ❤️'
        - 'Yes, I am a tier-4 patron ❤️  💙'
        - 'Yes, I am a tier-8 patron ❤️  💙 💜'
        - 'No, I am not 😞'
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context or screenshots you think will be helpful here.
  - type: markdown
    attributes:
      value: |
        Please keep in mind that **FreeSewing is a community project** that depends on **[your support](https://freesewing.org/community/join/)**.
---

