---
name: 🎖️ All Contributors update
description: Help capture the various contributions to FreeSewing
title: '[all contributors]: Please add (username here)'
labels: [':purple_heart: all contributors']
assignees: ['joostdecock']
body:
  - type: markdown
    attributes:
      value: 'FreeSewing is an [All Contributors](https://allcontributors.org/) project. Anybody can nominate someone to be added to our contributors list. Fill in the form below to do so :point_down:'
  - type: input
    id: username
    attributes:
      label: 'Who made the contribution(s)? 🤔'
      description: Please enter the Github username of the person who made the contribution(s)
      placeholder: 'joostdecock'
  - type: dropdown
    id: design
    attributes:
      label: 'What type(s) of contribution(s) did they make? 🧐'
      description: Check the emoji list and descriptions below and select whatever is appropriate
      multiple: true
      options:
        - '♿️ a11y: Reporting or working on accessibility issues'
        - '🐛 bug: Reporting or working on bugs'
        - '📝 blog: Writing blog posts'
        - '💻 code: Writing or improving our code'
        - '🖋 content: Showcase posts, newsletters, social media, and so on (not documentation or blog)'
        - '📖 doc: Documentation'
        - '🎨 design: Pattern design, but also UI/UX'
        - '📋 eventOrganizing: Organizing events and meetups'
        - '💵 financial: Provding financial support'
        - '🚇 infra: Hosting, Servers, SaaS, etc.'
        - '🚧 maintenance: Reserved for maintainers who do a bit of everything'
        - '🧑‍🏫 mentoring: Mentoring of new contributors'
        - '📦 platform: Providing specific platform support (Linux/Mac/Windows)'
        - '🔌 plugin: Writing/improving plugins'
        - '📆 projectManagement: Coordinating work'
        - '💬 question: Answering Questions in Issues, on Discord, etc.'
        - '👀 review: Reviewing Pull Requests'
        - '🛡️ security: Identify and/or reduce security threats, GDPR, Privacy, etc'
        - '🔧 tool: Work on tooling'
        - '🌍 translation: Providing translations'
        - '⚠️ test: People who write tests'
        - '✅ tutorial: Creating tutorials'
        - '📢 talk: Giving talks or presentations'
        - '📓 userTesting: End-to-end testing'
        - '📹 video: Making videos'
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: If there is any other info or pictures you'd like to add you can do so here
  - type: markdown
    attributes:
      value: Please keep in mind that **FreeSewing is a community project** that depends on **[your support](https://freesewing.org/community/join/)**.
---

